[package]
name = "ai_chat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openai-api = "0.1.5-alpha.0"

[patch.crates-io]
openai-api = { path = "./openai-api-rust" }